version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cortex-m
    versions:
    - 0.6.4
  - dependency-name: alloc-cortex-m
    versions:
    - 0.4.0
