[package]
authors = ["Dylan Frankland <github@frankland.io>"]
edition = "2018"
name = "proton-c"
readme = "README.md"
version = "0.1.0"
[[bin]]
bench = false
name = "proton-c"
test = false

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.5"
cortex-m-semihosting = "0.3.2"
panic-halt = "0.2.0"
stm32f3 = { version = "0.6.0", features = ["stm32f303", "rt"] }
[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"
